---
title: "Compassionate Critical Analysis"
author: "Jilly MacKay"
date: "3rd January 2020"
output: 
  slidy_presentation:
      highlight: haddock
      theme: flatly
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Critical Analysis

Critical analysis is an important aspect of academic discourse. It is often one of the elements considered in a marking scheme. 

If you are asked to 

- Evaluate
- Critique
- Analyse
- Conclude
- Discuss 
- Illustrate
- Judge
- Defend
- Appraise
- Develop
- Design


You are going to need to use your critical analysis skills. 

## Critical Analysis Is Not . . .

Critical analysis is not a personal attack. 

It does not imply you know everything about a topic. 

Critical analysis does not mean you disagree with the conclusions of a piece of work. 



## Features of Critical Analysis

Critical analysis is a lot like feedback. You should identify specific, fair and reasonable criticisms of a piece of work. 



*Specific*

- The critique should relate to your thesis. If you are trialing a new methodology, you will likely be focussing on flaws with current methodologies in the literature. 


*Reasonable* 

- The critique should make it clear why you might think a prior conclusion is right or wrong. It should relate to the specific issue you are concerned with, and explain the impact.


*Fair* 

- In your critique you should not assume you know the motivations or intent of the original person. Avoid phrases like "the authors clearly didn't understand the importance of X", and instead consider how your own evaluation may be be worng




## Critical Examples
Read these two examples of academic writing. 

### Example One
Academics like to eat cake (Rhind, 2001; MacKay et al. 2016) with cupcakes and brownies favoured at a consumption rate almost twice that of whole cakes (Hughes, 2015). Hughes speculated that this was because 'bite size' chunks of cake were easier for office guests to take. Individual service sizes are therefore more popular in offices (Pollock et al, 2009) 

### Example Two
Rhind (2001) observed that cakes left in an academic common area were quickly eaten, and stated that it was 'common knowledge' that academics like cake. Quanitfying cake eating in the office is challenging as several different cake types are commonly observed, with Hughes (2015) noting noting that cupcakes and brownies were consumed almost twice as quickly as whole cakes in two out of three observed academic study areas. The relationship between cake type and consumption rate makes it difficult to compare over time. MacKay et al (2016) recently explored cake depreciation rates in the office and found that cake consumption has remained at least as high as the levels observed in 2001, although they did not distinguish between cake types as Hughes did, which may make this an overestimate as we expect cupcakes have grown in popularity in line with other individual-portion confectionaries in offices (Pollock et al, 2009).


## Critical Examples | What's the difference?

Example Two is a better example of critical analysis. It is specific, fair and reasonable. 

Example two *specifically* focusses on the issue of cake types, and the issues this causes in drawing a conclusion about academics and cake eating.


### Specific
Rhind (2001) observed that cakes left in an academic common area were quickly eaten, and stated that it was 'common knowledge' that academics like cake. <font color = "blue">Quanitfying cake eating in the office is challenging as several different cake types are commonly observed</font>, with Hughes (2015) noting noting that cupcakes and brownies were consumed almost twice as quickly as whole cakes in two out of three observed academic study areas. <font color = "blue">The relationship between cake type and consumption rate makes it difficult to compare over time</font>. MacKay et al (2016) recently explored cake depreciation rates in the office and found that cake consumption has remained at least as high as the levels observed in 2001, <font color = "blue">although they did not distinguish between cake types as Hughes did</font>, which may make this an overestimate as we expect cupcakes have grown in popularity in line with other individual-portion confectionaries in offices (Pollock et al, 2009).


## Critical Examples | What's the difference?

Reasonable observations of the methodology highlight why we might disbelieve some of the conclusions. There may be other aspects of the studies that are worthy of critique, but as we are specifically looking at cake type, these are critiques which might explain why cake type is currently not fully considered. 

### Reasonable
Rhind (2001) observed that cakes left in an academic common area were quickly eaten, and stated that it was 'common knowledge' that academics like cake. Quanitfying cake eating in the office is challenging as several different cake types are commonly observed, with Hughes (2015) noting noting that cupcakes and brownies were consumed almost twice as quickly as whole cakes in <font color = "blue">two out of three observed academic study areas</font>. The relationship between cake type and consumption rate makes it difficult to compare over time. MacKay et al (2016) recently explored cake depreciation rates in the office and found that cake consumption has remained at least as high as the levels observed in 2001, <font color = "blue">although they did not distinguish between cake types</font> as Hughes did, which may make this an overestimate as we expect cupcakes have grown in popularity in line with other individual-portion confectionaries in offices (Pollock et al, 2009).


## Critical Examples | What's the difference?

The writing does not say 'always' or 'ever', but instead suggests where errors may exist and explains what the issue may be (e.g. that this could be an overestimate)

### Fair
Rhind (2001) observed that cakes left in an academic common area were quickly eaten, and stated that it was 'common knowledge' that academics like cake. Quanitfying cake eating in the office is challenging as several different cake types are commonly observed, with Hughes (2015) noting noting that cupcakes and brownies were consumed almost twice as quickly as whole cakes in two out of three observed academic study areas. The relationship between cake type and consumption rate makes it difficult to compare over time. MacKay et al (2016) recently explored cake depreciation rates in the office and found that cake consumption has remained at least as high as the levels observed in 2001, although they did not distinguish between cake types as Hughes did, <font color = "blue">which may make this an overestimate as we expect cupcakes have grown in popularity in line with other individual-portion confectionaries in offices</font> (Pollock et al, 2009).


## Exercise

(Discussion exercise of critical analysis?)